
package Network;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;



public class ServerGUI extends javax.swing.JFrame {

    boolean serverHasStart = false;
    Server server = null;

    /**
     * Creates new form ServerGUI
     */
    public ServerGUI() {
        initComponents();
        initDisplay();
        initThread();
        catchEvent(server);
    }

    public boolean isServerHasStart() {
        return serverHasStart;
    }

    public void setServerHasStart(boolean serverHasStart) {
        this.serverHasStart = serverHasStart;
    }

    public Server getServer() {
        return server;
    }

    public void setServer(Server server) {
        this.server = server;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        startServer = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        historyAdmin = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        broadcast = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        time_sys = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        darkbtn = new javax.swing.JButton();
        lightBtn = new javax.swing.JButton();

        jLabel9.setFont(new java.awt.Font("Arimo", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(20, 147, 188));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADMIN Chat App");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(254, 254, 254));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 231, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 239), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 185, 64));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("START");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, -1));

        startServer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-start-64.png"))); // NOI18N
        startServer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startServerMouseClicked(evt);
            }
        });
        jPanel2.add(startServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 120));

        jPanel3.setBackground(new java.awt.Color(19, 177, 225));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 239), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HISTORY");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, -1));

        historyAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historyAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-message-64.png"))); // NOI18N
        historyAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyAdminMouseClicked(evt);
            }
        });
        jPanel3.add(historyAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 119, -1, 120));

        jPanel4.setBackground(new java.awt.Color(225, 146, 19));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 239), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arimo", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BROADCAST");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        broadcast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        broadcast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-history-64.png"))); // NOI18N
        broadcast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                broadcastMouseClicked(evt);
            }
        });
        jPanel4.add(broadcast, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 119, -1, 120));

        jPanel5.setBackground(new java.awt.Color(1, 1, 1));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 239), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LOGOUT");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, -1));

        logoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-logout-rounded-down-60.png"))); // NOI18N
        jPanel5.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        background.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 119, -1, 120));

        time_sys.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        time_sys.setForeground(new java.awt.Color(1, 184, 49));
        time_sys.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time_sys.setText("00:00:00 dd/mm/yyyy");
        background.add(time_sys, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 818, -1));

        jPanel6.setBackground(new java.awt.Color(19, 144, 225));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 239), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("USER");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, -1));

        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-group-64.png"))); // NOI18N
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
        });
        jPanel6.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        background.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 119, -1, 120));

        message.setBackground(new java.awt.Color(1, 1, 1));
        message.setColumns(20);
        message.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        message.setForeground(new java.awt.Color(65, 156, 4));
        message.setLineWrap(true);
        message.setRows(5);
        message.setText("\n");
        jScrollPane1.setViewportView(message);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 315, 720, 154));

        jLabel12.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Command:");
        background.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 269, -1, -1));

        darkbtn.setBackground(new java.awt.Color(1, 1, 1));
        darkbtn.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        darkbtn.setForeground(new java.awt.Color(254, 254, 254));
        darkbtn.setText("DARK");
        darkbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                darkbtnMouseClicked(evt);
            }
        });
        background.add(darkbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 83, 81, 30));

        lightBtn.setBackground(new java.awt.Color(254, 254, 254));
        lightBtn.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        lightBtn.setText("LIGHT");
        lightBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lightBtnMouseClicked(evt);
            }
        });
        background.add(lightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 83, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void darkbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_darkbtnMouseClicked
        // TODO add your handling code here:
        background.setBackground(Color.BLACK);
        this.message.setBackground(Color.WHITE);
        this.message.setForeground(Color.BLACK);
    }//GEN-LAST:event_darkbtnMouseClicked

    private void lightBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lightBtnMouseClicked
        // TODO add your handling code here:
        background.setBackground(Color.WHITE);
        this.message.setBackground(Color.BLACK);
        this.message.setForeground(Color.GREEN);
    }//GEN-LAST:event_lightBtnMouseClicked

    private void startServerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startServerMouseClicked
        // TODO add your handling code here:
        new Thread(new StartServer(server)).start();

    }//GEN-LAST:event_startServerMouseClicked

    private void broadcastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_broadcastMouseClicked
        // TODO add your handling code here:
        if (server == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chạy server !!!");
            return;
        }
        new BroadCast_Server(server.getListSocket(), message).setVisible(true);
    }//GEN-LAST:event_broadcastMouseClicked

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        // TODO add your handling code here:
        new AdminUserGUI(message).setVisible(true);
    }//GEN-LAST:event_userLabelMouseClicked

    private void historyAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyAdminMouseClicked
        // TODO add your handling code here:
        String tmp = message.getText();
        message.setText(tmp + "\nServer show log history");
        new LogAdmin().setVisible(true);
    }//GEN-LAST:event_historyAdminMouseClicked

    private class StartServer implements Runnable {

        Server server;

        public StartServer(Server server) {
            this.server = server;
        }

        @Override
        public void run() {
            if (serverHasStart) {

                String tmp = message.getText();
                message.setText(tmp + "\nCan't start :Server already running !!!");
                return;
            }
            setServerHasStart(true);

            server = new Server();
            setServer(server);
            String tmp = message.getText();
            message.setText(tmp + "\nServer start successfully...");
            new Thread(server).start();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            System.out.println("Lỗi giao diện " +ex.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel broadcast;
    private javax.swing.JButton darkbtn;
    private javax.swing.JLabel historyAdmin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lightBtn;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JTextArea message;
    private javax.swing.JLabel startServer;
    private javax.swing.JLabel time_sys;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables

    private void initDisplay() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.message.setEditable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    private void initThread() {
        new Thread(new Time_System(time_sys)).start();
    }

    private void catchEvent(Server sv) {

        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                closeServer();
            }
        });

        logoutLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                closeServer();
            }
        });
    }

    private void closeServer() {
        int choose = JOptionPane.showConfirmDialog(null, "Bạn có muốn tắt server ?. Việc này sẽ khiến tất cả người dùng ngừng hoạt động ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (choose != 0) {
            return;
        }
        System.exit(0);
    }

    private static class Time_System implements Runnable {

        JLabel time;

        public Time_System(JLabel time) {
            this.time = time;
        }

        @Override
        public void run() {
            int index = 0;
            while (2 > 1) {
                try {
                    String colorStr[] = {"#ff00ff", "#ff0d00", "#ff6f00", "#bbd400", "#41b000", "#009c77", "#007f9c", "#002fff", "#8502e8"};
                    String timeStr = LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss dd:MM-yyyy"));

                    Color color = Color.decode(colorStr[index++]);
                    time.setText(timeStr);
                    time.setForeground(color);

                    if (index >= colorStr.length) {
                        index = 0;
                    }
                    Thread.sleep(1000);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Liỗ khi hiển thị thời gian hệ thống");
                }
            }
        }

    }

}
